apiVersion: v1
kind: Secret
metadata:
  name: autoflow-secrets
type: Opaque
data:
  POSTGRES_DB: YXV0b2Zsb3dfZGI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: OGFGM21LOXBRMnhWN25SdDVZY1cxekxiNERzSDZqVGUwVXJOOGdYcDNDdk03cUF6OUZrUDJoWXM2QndMZDRYZQ==
  MAIL_PASSWORD: bGVtdyBmbHdlIHZhYXcgbGRscw==
  APP_PUBLIC_TOKEN_SECRET: ZGV2LWxvY2FsLXNlY3JldA==