apiVersion: v1
kind: ConfigMap
metadata: 
  name: autoflow-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://${rds_address}:5432/autoflow_db
  JWT_EXPIRATION: "3600000"
  MAIL_USERNAME: autoflow.sistema@gmail.com
  POSTGRES_DB: autoflow_db

