apiVersion: v1
kind: Secret
metadata:
  name: autoflow-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: ${db_password}
  SPRING_DATASOURCE_USERNAME: ${db_username}
data:
  JWT_SECRET: OGFGM21LOXBRMnhWN25SdDVZY1cxekxiNERzSDZqVGUwVXJOOGdYcDNDdk03cUF6OUZrUDJoWXM2QndMZDRYZQ==
  MAIL_PASSWORD: bGVtdyBmbHdlIHZhYXcgbGRscw==
  APP_PUBLIC_TOKEN_SECRET: ZGV2LWxvY2FsLXNlY3JldA==