ALTER TABLE orcamento_item_necessario_item
    ADD COLUMN IF NOT EXISTS servico_os_id BIGINT;

ALTER TABLE ordem_servico
    ADD COLUMN execucao_iniciada_em TIMESTAMP,
    ADD COLUMN finalizada_em TIMESTAMP;

ALTER TABLE ordem_servico_servico_solicitado
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'AGUARDANDO',
    ADD COLUMN iniciado_em TIMESTAMP,
    ADD COLUMN finalizado_em TIMESTAMP;

ALTER TABLE ordem_servico_servico_solicitado
    DROP CONSTRAINT ordem_servico_servico_solicitado_pkey;

ALTER TABLE ordem_servico_servico_solicitado
    ADD CONSTRAINT pk_ordem_servico_servico_solicitado PRIMARY KEY (id);

ALTER TABLE ordem_servico_servico_solicitado
    ADD CONSTRAINT chk_os_servico_status
        CHECK (status IN ('AGUARDANDO', 'EM_EXECUCAO', 'FINALIZADO', 'CANCELADO'));

CREATE TABLE ordem_servico_servico_item_necessario (
    servico_solicitado_id BIGINT NOT NULL,
    peca_insumo_id BIGINT NOT NULL,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    valor_unitario NUMERIC(19, 2) NOT NULL,
    quantidade INTEGER NOT NULL,
    valor_total NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    ordem INTEGER NOT NULL,

    PRIMARY KEY (servico_solicitado_id, ordem),

    CONSTRAINT fk_servico_item_servico_solicitado
        FOREIGN KEY (servico_solicitado_id)
            REFERENCES ordem_servico_servico_solicitado(id)
            ON DELETE CASCADE,

    CONSTRAINT chk_servico_item_tipo
        CHECK (tipo IN ('PECA', 'INSUMO')),

    CONSTRAINT chk_servico_item_status
        CHECK (status IN ('DISPONIVEL', 'PENDENTE', 'UTILIZADO', 'CANCELADO'))
);
