name: CI Security and Analytics

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "develop", "main" ]

jobs:
   snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read       # Resolve o erro de acesso ao workflow-runs
      contents: read      # Permite ler o código para análise
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk Open Source Scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --sarif-file-output=snyk.sarif

      - name: Build Docker Image for Scan
        run: docker build -t autoflow-app:latest .

      - name: Snyk Container Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test autoflow-app:latest --file=Dockerfile

   sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BrunoSousa06_autoflow -Dsonar.qualitygate.wait=true -Dsonar.sources=src/main/java -Dsonar.tests=src/test/java