name: Pipeline

on:
  push:
    branches: ["develop", "main"]

  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["develop", "main"]

jobs:

  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run Unit Tests
        working-directory: backend
        run: mvn clean test

      - name: Upload Backend Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage
          path: backend/target/site/jacoco/
          if-no-files-found: ignore

  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    needs: backend-test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build Backend
        working-directory: backend
        run: mvn package -DskipTests

  backend-sonar:
    name: Backend SonarQube
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Run Sonar Analysis
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -DskipTests \
            -Dsonar.projectKey=BrunoSousa06_autoflow \
            -Dsonar.qualitygate.wait=true

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm run test:ci

      - name: Upload Frontend Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-coverage
          path: frontend/coverage/frontend
          if-no-files-found: ignore

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: frontend-test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    needs:  [backend-sonar, frontend-build]
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Snyk CLI
        uses: snyk/actions/setup@v4

      - name: Run Snyk Open Source Scan
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --sarif-file-output=snyk.sarif

      - name: Build Docker Image for Scan
        working-directory: backend
        run: docker build -t autoflow-app:latest -f Dockerfile .

      - name: Run Snyk Container Scan
        continue-on-error: true
        working-directory: backend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test autoflow-app:latest --file=Dockerfile

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs:  [backend-sonar, frontend-build]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: autoflow-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: autoflow-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max